### ISSUE TITLE
`_find_intersect_impl` is not type-stable

### ISSUE THREAD

**Issue by fhagemann** [JuliaPhysics/RadiationDetectorDSP.jl#35]
https://github.com/JuliaPhysics/RadiationDetectorDSP.jl/blob/22237d739bbbfe2fbfb4b1d58db0f61b32811e86/src/intersect.jl#L31-L75

If the signal in the `RDWaveform` is empty, the function returns `NaN` (L.38),
otherwise it returns a `NamedTuple` with `x` and `multiplicity` (L. 71-74).

One possible way to fix this could be to return `(x = NaN, multiplicity = -1)` if the signal is empty.

**Comment by oschulz** [comment]
Good idea!

**Comment by fhagemann** [comment]
Should I make a PR or will you take care of this? @oschulz

**Comment by oschulz** [comment]
I'm on it.
